import { MARKETS } from './marketData';

const currencyMap: Record<string, string> = {
  US: 'USD', PK: 'PKR', UK: 'GBP', AE: 'AED',
};

export function formatCurrency(value: number, country: string = 'US'): string {
  const currency = currencyMap[country] || 'USD';
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  } catch {
    return `${currency} ${Math.round(value).toLocaleString()}`;
  }
}

export function parseNumericInput(value: string): number {
  return parseFloat(value.replace(/[^0-9.\-]/g, '')) || 0;
}

export function formatWithCommas(value: string): string {
  const num = value.replace(/[^0-9]/g, '');
  return num.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

export function generateExportMemo(params: {
  type: string;
  inputs: Record<string, string>;
  results: Record<string, string>;
  qualityScore?: number;
  decision?: string;
  analysis?: string;
  aiAnalysis?: string;
  industry: string;
  country: string;
  scenario: string;
}): string {
  const market = MARKETS[params.country]?.name || params.country;
  const date = new Date();
  const dateStr = date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const formatKey = (k: string) =>
    k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()).trim();

  const inputLines = Object.entries(params.inputs).map(([k, v]) => `  ${formatKey(k).padEnd(24)} ${v}`).join('\n');
  const resultLines = Object.entries(params.results).map(([k, v]) => `  ${formatKey(k).padEnd(24)} ${v}`).join('\n');

  return `
═══════════════════════════════════════════════════════════
                    INVESTMENT MEMORANDUM
                        CONFIDENTIAL
═══════════════════════════════════════════════════════════

TO:        Investment Committee
FROM:      Alight Financial Analysis
DATE:      ${dateStr}
RE:        ${params.type} Analysis — ${params.industry.replace('-', ' ').replace(/\b\w/g, c => c.toUpperCase())} / ${market}

═══════════════════════════════════════════════════════════
I. EXECUTIVE SUMMARY
═══════════════════════════════════════════════════════════

  Recommendation:        ${params.decision || 'N/A'}
  Quality Score:         ${params.qualityScore != null ? `${params.qualityScore}/10` : 'N/A'}
  Scenario:              ${params.scenario.toUpperCase()}
  Market:                ${market}
  Sector:                ${params.industry.replace('-', ' ').replace(/\b\w/g, c => c.toUpperCase())}

═══════════════════════════════════════════════════════════
II. TRANSACTION OVERVIEW
═══════════════════════════════════════════════════════════

${inputLines}

═══════════════════════════════════════════════════════════
III. FINANCIAL ANALYSIS
═══════════════════════════════════════════════════════════

${resultLines}

═══════════════════════════════════════════════════════════
IV. MARKET POSITIONING & COMMENTARY
═══════════════════════════════════════════════════════════

${params.analysis || 'N/A'}

═══════════════════════════════════════════════════════════
V. AI-ASSISTED DEEP ANALYSIS
═══════════════════════════════════════════════════════════

${params.aiAnalysis || 'AI analysis not available for this calculation.'}

═══════════════════════════════════════════════════════════
VI. METHODOLOGY & DISCLAIMERS
═══════════════════════════════════════════════════════════

  • IRR calculated using bisection method with interim cash flows
  • MOIC includes all distributions (operations + exit)
  • Quality score uses standardized methodology (performance,
    risk, time efficiency)
  • Scenario analysis: Bull +30% / Bear -25% on primary metric
  • Valuation ranges based on percentile methodology (25th,
    50th, 75th)
  • AI analysis powered by Alight's proprietary models and
    should be used as supplementary guidance only

  This memorandum is prepared for informational purposes and
  does not constitute investment advice. Past performance is
  not indicative of future results. All projections are
  estimates based on the inputs provided.

═══════════════════════════════════════════════════════════
                        CONFIDENTIAL
        Generated by Alight Financial Calculator
        © 2026 Aliyan Arman. All rights reserved.
═══════════════════════════════════════════════════════════
`.trim();
}

export function downloadMemo(memo: string) {
  const blob = new Blob([memo], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Investment_Memo_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
