import { MARKETS } from './marketData';
import jsPDF from 'jspdf';

const currencyMap: Record<string, string> = {
  US: 'USD', PK: 'PKR', UK: 'GBP', AE: 'AED',
};

export function formatCurrency(value: number, country: string = 'US'): string {
  const currency = currencyMap[country] || 'USD';
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  } catch {
    return `${currency} ${Math.round(value).toLocaleString()}`;
  }
}

export function parseNumericInput(value: string): number {
  return parseFloat(value.replace(/[^0-9.\-]/g, '')) || 0;
}

export function formatWithCommas(value: string): string {
  const num = value.replace(/[^0-9]/g, '');
  return num.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

export async function fetchDetailedAnalysis(params: {
  calculatorType: string;
  inputs: Record<string, string | number>;
  results: Record<string, string | number>;
  industry: string;
  country: string;
}): Promise<string> {
  try {
    const url = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ai-deal-analysis`;
    const resp = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
      },
      body: JSON.stringify({ ...params, detailedMemo: true }),
    });
    if (!resp.ok) return 'Detailed analysis unavailable.';
    const data = await resp.json();
    return data.analysis || 'Detailed analysis unavailable.';
  } catch {
    return 'Detailed analysis unavailable.';
  }
}

export function generateExportMemo(params: {
  type: string;
  inputs: Record<string, string>;
  results: Record<string, string>;
  qualityScore?: number;
  decision?: string;
  analysis?: string;
  aiAnalysis?: string;
  industry: string;
  country: string;
  scenario: string;
}): string {
  const market = MARKETS[params.country]?.name || params.country;
  const date = new Date();
  const dateStr = date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const formatKey = (k: string) =>
    k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()).trim();

  const inputLines = Object.entries(params.inputs).map(([k, v]) => `  ${formatKey(k).padEnd(24)} ${v}`).join('\n');
  const resultLines = Object.entries(params.results).map(([k, v]) => `  ${formatKey(k).padEnd(24)} ${v}`).join('\n');

  return `
INVESTMENT MEMORANDUM — CONFIDENTIAL

TO:        Investment Committee
FROM:      Alight Financial Analysis
DATE:      ${dateStr}
RE:        ${params.type} Analysis — ${params.industry.replace('-', ' ').replace(/\b\w/g, c => c.toUpperCase())} / ${market}

I. EXECUTIVE SUMMARY
  Recommendation:        ${params.decision || 'N/A'}
  Quality Score:         ${params.qualityScore != null ? `${params.qualityScore}/10` : 'N/A'}
  Scenario:              ${params.scenario.toUpperCase()}
  Market:                ${market}
  Sector:                ${params.industry.replace('-', ' ').replace(/\b\w/g, c => c.toUpperCase())}

II. TRANSACTION OVERVIEW
${inputLines}

III. FINANCIAL ANALYSIS
${resultLines}

IV. MARKET ANALYSIS & COMMENTARY
${params.analysis || 'N/A'}

V. DETAILED AI ANALYSIS
${params.aiAnalysis || 'AI analysis not available.'}

VI. DISCLAIMERS
  This memorandum is prepared for informational purposes only.
  Generated by Alight Financial Calculator.
  © 2026 Aliyan Arman. All rights reserved.
`.trim();
}

export async function downloadMemoPDF(params: {
  type: string;
  inputs: Record<string, string>;
  results: Record<string, string>;
  qualityScore?: number;
  decision?: string;
  analysis?: string;
  industry: string;
  country: string;
  scenario: string;
  calculatorInputs: Record<string, string | number>;
  calculatorResults: Record<string, string | number>;
}) {
  const market = MARKETS[params.country]?.name || params.country;
  const date = new Date();
  const dateStr = date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const sectorName = params.industry.replace('-', ' ').replace(/\b\w/g, c => c.toUpperCase());

  // Fetch detailed AI analysis for PDF
  const detailedAnalysis = await fetchDetailedAnalysis({
    calculatorType: params.type,
    inputs: params.calculatorInputs,
    results: params.calculatorResults,
    industry: params.industry,
    country: params.country,
  });

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const marginL = 22;
  const marginR = 22;
  const contentW = pageW - marginL - marginR;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > 270) { doc.addPage(); y = 20; }
  };

  // Header bar
  doc.setFillColor(15, 15, 15);
  doc.rect(0, 0, pageW, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('CONFIDENTIAL', pageW - marginR, 12, { align: 'right' });
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('INVESTMENT MEMORANDUM', marginL, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${params.type} Analysis — ${sectorName} / ${market}`, marginL, 28);
  doc.setFontSize(8);
  doc.text(dateStr, pageW - marginR, 28, { align: 'right' });

  y = 48;
  doc.setTextColor(40, 40, 40);

  // Section I: Executive Summary
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('I.  EXECUTIVE SUMMARY', marginL, y);
  y += 2;
  doc.setDrawColor(40, 40, 40);
  doc.setLineWidth(0.5);
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const summaryItems = [
    ['Recommendation', params.decision || 'N/A'],
    ['Quality Score', params.qualityScore != null ? `${params.qualityScore} / 10` : 'N/A'],
    ['Scenario', params.scenario.toUpperCase()],
    ['Market', market],
    ['Sector', sectorName],
  ];
  summaryItems.forEach(([label, val]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, marginL + 4, y);
    doc.setFont('helvetica', 'normal');
    doc.text(val, marginL + 50, y);
    y += 6;
  });
  y += 6;

  // Section II: Transaction Overview
  checkPage(40);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('II.  TRANSACTION OVERVIEW', marginL, y);
  y += 2;
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  doc.setFontSize(9);
  Object.entries(params.inputs).forEach(([k, v]) => {
    checkPage(8);
    doc.setFont('helvetica', 'bold');
    doc.text(k, marginL + 4, y);
    doc.setFont('helvetica', 'normal');
    doc.text(v, pageW - marginR, y, { align: 'right' });
    y += 6;
  });
  y += 6;

  // Section III: Financial Analysis
  checkPage(40);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('III.  FINANCIAL ANALYSIS', marginL, y);
  y += 2;
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  doc.setFontSize(9);
  // Table header
  doc.setFillColor(240, 240, 240);
  doc.rect(marginL, y - 4, contentW, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Metric', marginL + 4, y);
  doc.text('Value', pageW - marginR - 4, y, { align: 'right' });
  y += 8;

  doc.setFont('helvetica', 'normal');
  let rowIdx = 0;
  Object.entries(params.results).forEach(([k, v]) => {
    checkPage(8);
    if (rowIdx % 2 === 1) {
      doc.setFillColor(248, 248, 248);
      doc.rect(marginL, y - 4, contentW, 7, 'F');
    }
    doc.text(k, marginL + 4, y);
    doc.text(v, pageW - marginR - 4, y, { align: 'right' });
    y += 7;
    rowIdx++;
  });
  y += 8;

  // Section IV: In-App Analysis
  if (params.analysis) {
    checkPage(30);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('IV.  MARKET POSITIONING', marginL, y);
    y += 2;
    doc.line(marginL, y, pageW - marginR, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const analysisLines = doc.splitTextToSize(params.analysis, contentW - 8);
    analysisLines.forEach((line: string) => {
      checkPage(6);
      doc.text(line, marginL + 4, y);
      y += 5;
    });
    y += 8;
  }

  // Section V: Detailed AI Analysis with Market Comparables
  checkPage(30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('V.  DETAILED ANALYSIS & MARKET COMPARABLES', marginL, y);
  y += 2;
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const detailedLines = doc.splitTextToSize(detailedAnalysis, contentW - 8);
  detailedLines.forEach((line: string) => {
    checkPage(6);
    doc.text(line, marginL + 4, y);
    y += 5;
  });
  y += 8;

  // Section VI: Disclaimers
  checkPage(30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('VI.  METHODOLOGY & DISCLAIMERS', marginL, y);
  y += 2;
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const disclaimers = [
    'IRR calculated using bisection method with interim cash flows.',
    'MOIC includes all distributions (operations + exit).',
    'Quality score uses standardized methodology (performance, risk, time efficiency).',
    'Scenario analysis: Bull +30% / Bear -25% on primary metric.',
    'AI analysis powered by Alight\'s models and should be used as supplementary guidance only.',
    'This memorandum is prepared for informational purposes and does not constitute investment advice.',
    'Past performance is not indicative of future results.',
  ];
  disclaimers.forEach(d => {
    checkPage(6);
    doc.text(`•  ${d}`, marginL + 4, y);
    y += 5;
  });

  // Footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(15, 15, 15);
    doc.rect(0, 282, pageW, 15, 'F');
    doc.setTextColor(180, 180, 180);
    doc.setFontSize(7);
    doc.text('CONFIDENTIAL — Generated by Alight Financial Calculator', marginL, 289);
    doc.text(`© 2026 Aliyan Arman  |  Page ${i} of ${totalPages}`, pageW - marginR, 289, { align: 'right' });
  }

  doc.save(`Investment_Memo_${params.type.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}

// Keep legacy text download for backward compat
export function downloadMemo(memo: string) {
  const blob = new Blob([memo], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Investment_Memo_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
