import { MARKETS } from './marketData';

const currencyMap: Record<string, string> = {
  US: 'USD', PK: 'PKR', UK: 'GBP', AE: 'AED',
};

// FIXED: Uses correct currency symbol based on country
export function formatCurrency(value: number, country: string = 'US'): string {
  const currency = currencyMap[country] || 'USD';
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  } catch {
    return `${currency} ${Math.round(value).toLocaleString()}`;
  }
}

export function parseNumericInput(value: string): number {
  return parseFloat(value.replace(/[^0-9.\-]/g, '')) || 0;
}

export function formatWithCommas(value: string): string {
  const num = value.replace(/[^0-9]/g, '');
  return num.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

// Improved export memo with full analysis
export function generateExportMemo(params: {
  type: string;
  inputs: Record<string, string>;
  results: Record<string, string>;
  qualityScore?: number;
  decision?: string;
  analysis?: string;
  industry: string;
  country: string;
  scenario: string;
}): string {
  const market = MARKETS[params.country]?.name || params.country;

  const formatKey = (k: string) =>
    k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()).trim();

  return `
INVESTMENT MEMORANDUM
═══════════════════════════════════════════════

Date: ${new Date().toLocaleString()}
Market: ${market}
Industry: ${params.industry.replace('-', ' ').toUpperCase()}
Analysis: ${params.type}
Scenario: ${params.scenario.toUpperCase()}

─── DEAL INPUTS ───
${Object.entries(params.inputs).map(([k, v]) => `${formatKey(k)}: ${v}`).join('\n')}

─── CALCULATED RESULTS ───
${Object.entries(params.results).map(([k, v]) => `${formatKey(k)}: ${v}`).join('\n')}

─── QUALITY ASSESSMENT ───
${params.qualityScore != null ? `Quality Score: ${params.qualityScore}/10` : ''}
${params.decision ? `Decision: ${params.decision}` : ''}

─── MARKET ANALYSIS ───
${params.analysis || 'N/A'}

─── METHODOLOGY NOTES ───
• IRR calculated using bisection method with interim cash flows
• MOIC includes all distributions (operations + exit)
• Quality score uses standardized methodology (performance, risk, time)
• Scenario analysis: Bull +30% / Bear -25% on primary metric

═══════════════════════════════════════════════
Generated by Alight Financial Calculator
Confidential - Not for distribution
`.trim();
}

export function downloadMemo(memo: string) {
  const blob = new Blob([memo], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Investment_Memo_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
